##### APP
FROM debian:latest

RUN apt-get update
RUN apt-get install -y sudo git wget curl unzip
RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN apt-get install -y nodejs
RUN npm install -g cordova
RUN npm install -g ionic
COPY ./ /root/guide/app
WORKDIR /root/guide/app
RUN npm install

EXPOSE 8100
EXPOSE 35729
CMD ionic serve --all




